package com.niet.analytics.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * Encapsulates the complete Risk Assessment for a student.
 * Generated by the At-Risk Identification Algorithm.
 */
public class RiskReport implements Serializable {
    private static final long serialVersionUID = 1L;

    private String studentId;
    private String studentName;
    private String erpId;
    private String section;
    private int semester;

    private double attendancePercentage;
    private double averageScorePercentage;
    private int failingSubjectCount;

    private double compositeRiskScore; // 0.0 (safest) to 100.0 (highest risk)
    private RiskLevel riskLevel;

    private List<String> riskFactors = new ArrayList<>();
    private List<String> recommendedInterventions = new ArrayList<>();
    private String evaluationDate;

    public RiskReport() {
        this.evaluationDate = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm"));
    }

    public RiskReport(String studentId, String studentName, String erpId, String section, int semester,
                      double attendancePercentage, double averageScorePercentage, int failingSubjectCount,
                      double compositeRiskScore, RiskLevel riskLevel) {
        this();
        this.studentId = studentId;
        this.studentName = studentName;
        this.erpId = erpId;
        this.section = section;
        this.semester = semester;
        this.attendancePercentage = attendancePercentage;
        this.averageScorePercentage = averageScorePercentage;
        this.failingSubjectCount = failingSubjectCount;
        this.compositeRiskScore = Math.round(compositeRiskScore * 10.0) / 10.0;
        this.riskLevel = riskLevel;
    }

    public void addRiskFactor(String factor) {
        riskFactors.add(factor);
    }

    public void addIntervention(String intervention) {
        recommendedInterventions.add(intervention);
    }

    // Getters and Setters
    public String getStudentId() {
        return studentId;
    }

    public void setStudentId(String studentId) {
        this.studentId = studentId;
    }

    public String getStudentName() {
        return studentName;
    }

    public void setStudentName(String studentName) {
        this.studentName = studentName;
    }

    public String getErpId() {
        return erpId;
    }

    public void setErpId(String erpId) {
        this.erpId = erpId;
    }

    public String getSection() {
        return section;
    }

    public void setSection(String section) {
        this.section = section;
    }

    public int getSemester() {
        return semester;
    }

    public void setSemester(int semester) {
        this.semester = semester;
    }

    public double getAttendancePercentage() {
        return attendancePercentage;
    }

    public void setAttendancePercentage(double attendancePercentage) {
        this.attendancePercentage = attendancePercentage;
    }

    public double getAverageScorePercentage() {
        return averageScorePercentage;
    }

    public void setAverageScorePercentage(double averageScorePercentage) {
        this.averageScorePercentage = averageScorePercentage;
    }

    public int getFailingSubjectCount() {
        return failingSubjectCount;
    }

    public void setFailingSubjectCount(int failingSubjectCount) {
        this.failingSubjectCount = failingSubjectCount;
    }

    public double getCompositeRiskScore() {
        return compositeRiskScore;
    }

    public void setCompositeRiskScore(double compositeRiskScore) {
        this.compositeRiskScore = compositeRiskScore;
    }

    public RiskLevel getRiskLevel() {
        return riskLevel;
    }

    public void setRiskLevel(RiskLevel riskLevel) {
        this.riskLevel = riskLevel;
    }

    public List<String> getRiskFactors() {
        return riskFactors;
    }

    public void setRiskFactors(List<String> riskFactors) {
        this.riskFactors = riskFactors;
    }

    public List<String> getRecommendedInterventions() {
        return recommendedInterventions;
    }

    public void setRecommendedInterventions(List<String> recommendedInterventions) {
        this.recommendedInterventions = recommendedInterventions;
    }

    public String getEvaluationDate() {
        return evaluationDate;
    }

    public void setEvaluationDate(String evaluationDate) {
        this.evaluationDate = evaluationDate;
    }
}
